ROLES = ["RECEPCION", "CAJA", "GERENCIA", "ADMINISTRADOR"]
CANALES = ["DIRECTO", "WEB", "TELEFONO", "AGENCIA", "OTA"]
METODOS_PAGO = ["EFECTIVO", "TARJETA", "TRANSFERENCIA", "YAPE_PLIN"]
ESTADOS_RESERVA = ["PENDIENTE", "CONFIRMADA", "CANCELADA", "NO_SHOW", "FINALIZADA"]
ESTADOS_RESERVA_TERMINALES = ("CANCELADA", "NO_SHOW", "FINALIZADA")
